{{- if .Values.config.password.sealed }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: "{{ .Release.Name }}-server-password"
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    password: {{ .Values.config.password.sealedValue }}
  template:
    metadata:
      name: "{{ .Release.Name }}-server-password"
      namespace: {{ .Release.Namespace }}
    type: Opaque
{{- else if .Values.config.password.value }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-server-password"
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  password: {{ .Values.config.password.value | quote }}
{{- end }}
